graph TD
  python3 --> python3-minimal
  python3-minimal --> dpkg
  dpkg --> liblzma5
  liblzma5 --> libc6
  libc6 --> libgcc-s1
  libgcc-s1 --> libc6
  libgcc-s1 --> gcc-14-base
  dpkg --> libzstd1
  libzstd1 --> libc6
  dpkg --> libbz2-1.0
  libbz2-1.0 --> libc6
  dpkg --> libselinux1
  libselinux1 --> libc6
  libselinux1 --> libpcre2-8-0
  libpcre2-8-0 --> libc6
  dpkg --> libc6
  dpkg --> zlib1g
  zlib1g --> libc6
  dpkg --> libmd0
  libmd0 --> libc6
  dpkg --> tar
  tar --> libacl1
  libacl1 --> libc6
  tar --> libc6
  tar --> libselinux1
  python3-minimal --> python3.12-minimal
  python3.12-minimal --> libc6
  python3.12-minimal --> libpython3.12-minimal
  libpython3.12-minimal --> libc6
  libpython3.12-minimal --> libssl3t64
  libssl3t64 --> libc6
  python3.12-minimal --> zlib1g
  python3.12-minimal --> libexpat1
  libexpat1 --> libc6
  python3 --> libpython3-stdlib
  libpython3-stdlib --> libpython3.12-stdlib
  libpython3.12-stdlib --> libtinfo6
  libtinfo6 --> libc6
  libpython3.12-stdlib --> libpython3.12-minimal
  libpython3.12-stdlib --> libreadline8t64
  libreadline8t64 --> readline-common
  libreadline8t64 --> libtinfo6
  libreadline8t64 --> libc6
  libpython3.12-stdlib --> liblzma5
  libpython3.12-stdlib --> libffi8
  libffi8 --> libc6
  libpython3.12-stdlib --> libbz2-1.0
  libpython3.12-stdlib --> tzdata
  tzdata --> debconf
  libpython3.12-stdlib --> media-types
  libpython3.12-stdlib --> libcrypt1
  libcrypt1 --> libc6
  libpython3.12-stdlib --> libsqlite3-0
  libsqlite3-0 --> libc6
  libpython3.12-stdlib --> netbase
  libpython3.12-stdlib --> libc6
  libpython3.12-stdlib --> libncursesw6
  libncursesw6 --> libtinfo6
  libncursesw6 --> libc6
  libpython3.12-stdlib --> libdb5.3t64
  libdb5.3t64 --> libc6
  python3 --> python3.12
  python3.12 --> libpython3.12-stdlib
  python3.12 --> tzdata
  python3.12 --> python3.12-minimal
  python3.12 --> media-types
  Repo[http://archive.ubuntu.com/ubuntu]